### ISSUE TITLE
Does the URL: https://github.com/commands-selfdriving-car/Talk2Car-dataset.git really exist?

### ISSUE THREAD

**Issue by kiitaamuuraa** [talk2car/Talk2Car#1]
I tried to do git clone by the following command, but the response was just "not found."
I would appreciate it if you could how to download the dataset.
* command 
`git clone https://github.com/commands-selfdriving-car/Talk2Car-dataset.git
`
* response
```
Cloning into 'Talk2Car-dataset'...
Username for 'https://github.com': ********************
Password for 'https://********************@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/commands-selfdriving-car/Talk2Car-dataset.git/' not found 
```

**Comment by ThierryDeruyttere** [comment]
There was an issue in the readme.md. It pointed to the old repo. This is fixed now.
The correct link is:

`git clone https://github.com/talk2car/Talk2Car.git`

**Comment by kiitaamuuraa** [comment]
Thanks for your promptly modifying it.
