### ISSUE TITLE
About the 3D label

### ISSUE THREAD

**Issue by dszpr** [talk2car/Talk2Car#12]
Hi, many thanks for the dataset!

Although the talk2car task is 2D, I notice that you provide 3D labels for each sample. However, I am confused about the 3D labels. Here are my questions:
1. What coordinate system is the 3D label based on? 
2. Is the rotation label a quaternion? 
3. How can I convert the 3D label into the form [x, y, z, w, l, h, yaw], specifically, how can I convert the provided rotation label into yaw?

Looking forward to your reply!

**Comment by ThierryDeruyttere** [comment]
these 3d labels come from the nuScenes dataset. More information about those labels can be found there

**Comment by dszpr** [comment]
Thanks, I will check nuScenes dataset.

**Comment by Zhao-Qihao** [comment]
> Thanks, I will check nuScenes dataset.

Hi, have you got the 3D labels? I have some troubles in getting the 3D labels of talk2car dataset
