### ISSUE TITLE
Which dataset should I use?

### ISSUE THREAD

**Issue by kiitaamuuraa** [talk2car/Talk2Car#2]
I know I should use "v1.0-trainval" from here:`super().__init__(version="v1.0-trainval", dataroot=dataroot, verbose=verbose).

However, I do not know which one on the [website](https://www.nuscenes.org/download) is what I should use.

![image](https://user-images.githubusercontent.com/6381904/100897561-6bdef280-3485-11eb-9c76-583f7b95b646.png)

Could you please tell me which one I should use?

Thanks,

**Comment by ThierryDeruyttere** [comment]
![image](https://user-images.githubusercontent.com/6353651/100903756-8dac9980-34c6-11eb-9830-ad7fda631d0a.png)
For all the 10 parts you will need to click on either "US" or "Asia".
Please note though that this will download a lot of images and other data that is not used in the Talk2Car dataset. If you want to download only the required images for Talk2Car and you are not interested in any of the other modalities, please look here: https://github.com/talk2car/Talk2Car/tree/master/c4av_model

**Comment by ThierryDeruyttere** [comment]
@kiitaamuuraa I've also updated the readme to reflect what I've just said.

**Comment by kiitaamuuraa** [comment]
I see; thank you!!
