### ISSUE TITLE
sample_token

### ISSUE THREAD

**Issue by cwhao98** [talk2car/Talk2Car#5]
Hi,

    Is the sample token strictly the same as that of the original nuScenes dataset ?

Thanks.

**Comment by ThierryDeruyttere** [comment]
Hi, 

Yes it is the same as that of the original nuScenes dataset.

Best,

Thierry

**Comment by cwhao98** [comment]
@ThierryDeruyttere  

Thanks for your reply.

But I still have doubts about the sample token.  Why did the following code report an error?

```
from nuscenes.nuscenes import NuScenes
nusc = NuScenes(version='v1.0-trainval', dataroot='nuScenes/data/root', verbose=True)
tmp_sample_token = 'c32d636e44604d77a1734386b3fe4a0d' # This token is got from https://github.com/talk2car/Talk2Car/tree/master/data
sample = nusc.get('sample', tmp_sample_token)
```
Thanks.

**Comment by ThierryDeruyttere** [comment]
@cwhao98 

```
sample = nusc.get('sample', tmp_sample_token)
````

should be

```
sample = nusc.get('sample_data', tmp_sample_token)
```

**Comment by cwhao98** [comment]
@ThierryDeruyttere 

Thanks! 

I got it !

**Comment by ThierryDeruyttere** [comment]
No problem :-) If you have any other questions, feel free to open other issues!
