### ISSUE TITLE
Keyerror: "i'm"

### ISSUE THREAD

**Issue by yuchen2199** [talk2car/Talk2Car#6]
Hi!
I follow all packages version as the requirement.txt(torch==1.8.1 torchvision==0.9.1 ....)
When I try to run the code as python3 train.py --root ./data --lr 0.01 --nesterov --evaluate，th are some bugs occur:

Keyerror: "i'm"

What can I do?

**Comment by ThierryDeruyttere** [comment]
Hi there!

This is very strange... Can you please check that you have spacy version 2.2.4 installed?
You can also compare with the following google collab to see if you have exactly the same packages: 
https://colab.research.google.com/drive/19wTtGskfdhZWvNIfIrUcpwe9IChRKBtQ?usp=sharing
Please let me know though if you use spacy version 2.2.4 because I'm truly interested to know where there might still be a problem.

**Comment by yuchen2199** [comment]
Yes！My spacy version is 2.2.4.

**Comment by ThierryDeruyttere** [comment]
Okay this is strange. Could you please do the following:

- Make sure you have anaconda installed
- Create a new directory where you want to install the Talk2car repository
- In this repository, create a file `setup.sh` and copy the following in that file.

``` 
# Create conda environment
conda create --name talk2car_baseline python=3.6 -y
echo "created conda environment 'talk2car_baseline'..."

source activate talk2car_baseline
echo "activating environment 'talk2car_baseline'..."

echo "installing 'gdown'..."
pip install gdown

# Download code
echo "downloading the code..."
git clone https://github.com/talk2car/Talk2Car.git

# Download data
echo "downloading the data..."
gdown --id 1bhcdej7IFj5GqfvXGrHGPk2Knxe77pek

# Unzip images to the correct directory
echo "preparing the data..."
unzip imgs.zip && mv imgs/ Talk2Car/c4av_model/data/images
rm imgs.zip

# Install requirements
echo "installing talk2car requirements..."
cd Talk2Car/c4av_model && pip install -r requirements.txt

echo "installing spacy's en_core_web_sm..."
python -m spacy download en_core_web_sm

python "start training..."
python3 train.py --root ./data --lr 0.01 --nesterov --evaluate
```

Then write `chmod +x setup.sh && ./setup.sh`.
Let me know if this still gives you an error

**Comment by ThierryDeruyttere** [comment]
FYI, we tested the above script on two different machines and we could fully train the model without any errors. Please let me know if the issue is resolved.
